---
- name: Write Syslog on switch to inform Ansible Start
  shell: /usr/bin/logger -t "ANSIBLE" "Update Routine starting."
  tags:
    - upgrade

- import_tasks: upgrade.yml
  tags:
    - upgrade

- import_tasks: shutdown_ospf.yml
  when: "'spines' in group_names or 'uplinks' in group_names"
  tags:
    - ospf

- import_tasks: shutdown_clag.yml
  when: "'spines' in group_names or 'leafs' in group_names"
  tags:
    - clag

- name: Write Syslog on switch to inform Ansible Finish
  shell: /usr/bin/logger -t "ANSIBLE" "Upgrade routine complete. Upgrade to commence now."
  notify: restart and upgrade
  tags:
    - upgrade
